### PR TITLE
docs: translated appendix-02-operators

### PR DESCRIPTION
**Pull request by mmnvb**
semi-manual work

### CODE REVIEW

**Comment by orzklv** [comment]
you alive mate?) @mmnvb

**Comment by mmnvb** [comment]
@orzklv 🥲yes

**Comment by orzklv** [comment]
aight, accepting the pr. btw, have you heard of sponsorship program i announced? 
https://t.me/rustlanguz/22990/26659

**Comment by mmnvb** [comment]
I've just checked it. That's really nice of you

**Comment by orzklv** [comment]
> I've just checked it. That's really nice of you

Wanna join?)

**Comment by mmnvb** [comment]
u mean the tg group or sponsorship program? i can't take money from you period

**Comment by orzklv** [comment]
sponsorship program. maybe join our localization movement?

**Comment by mmnvb** [comment]
yep, I will do my best to contribute

**Pull request merged**
